/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        surface: '#faf9f9',
        'surface-bright': '#faf9f9',
        'surface-dim': '#dbdad9',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f5f3f3',
        'surface-container': '#efeded',
        'surface-container-high': '#e9e8e8',
        'surface-container-highest': '#e3e2e2',
        'surface-variant': '#e3e2e2',
        'on-surface': '#1b1c1c',
        'on-surface-variant': '#444748',
        'inverse-surface': '#303031',
        'inverse-on-surface': '#f2f0f0',
        outline: '#747878',
        'outline-variant': '#c4c7c7',
        primary: '#000000',
        'on-primary': '#ffffff',
        'primary-container': '#1c1b1b',
        'on-primary-container': '#858383',
        secondary: '#9d422f',
        'on-secondary': '#ffffff',
        'secondary-container': '#fc8c74',
        'on-secondary-container': '#742414',
        'secondary-fixed': '#ffdad3',
        'secondary-fixed-dim': '#ffb4a4',
        tertiary: '#000000',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#1d1b1a',
        'on-tertiary-container': '#868381',
        'tertiary-fixed-dim': '#cac6c3',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        background: '#faf9f9',
        'on-background': '#1b1c1c',
      },
      borderRadius: {
        DEFAULT: '0px',
        sm: '0px',
        md: '0px',
        lg: '0px',
        xl: '0px',
        full: '0px',
        terminal: '6px',
      },
      spacing: {
        'margin-edge': '48px',
        'section-v-rhyme': '140px',
        gutter: '24px',
        'stack-xl': '44px',
        'stack-lg': '32px',
        'stack-md': '16px',
        'stack-sm': '8px',
      },
      fontFamily: {
        display: ['"Playfair Display"', 'Georgia', 'serif'],
        'headline-lg': ['"Playfair Display"', 'Georgia', 'serif'],
        'headline-lg-mobile': ['"Playfair Display"', 'Georgia', 'serif'],
        'headline-md': ['"Playfair Display"', 'Georgia', 'serif'],
        'body-lg': ['"Source Serif 4"', 'Georgia', 'serif'],
        'body-md': ['"Source Serif 4"', 'Georgia', 'serif'],
        kicker: ['"JetBrains Mono"', 'ui-monospace', 'monospace'],
        'mono-ui': ['"JetBrains Mono"', 'ui-monospace', 'monospace'],
      },
      fontSize: {
        display: ['60px', { lineHeight: '1.15', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-lg': ['48px', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-lg-mobile': ['36px', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-md': ['32px', { lineHeight: '1.3', fontWeight: '600' }],
        'body-lg': ['20px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['17px', { lineHeight: '1.6', fontWeight: '400' }],
        'mono-ui': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        kicker: ['12px', { lineHeight: '1.0', letterSpacing: '0.2em', fontWeight: '500' }],
      },
      maxWidth: {
        prose: '720px',
      },
    },
  },
  plugins: [],
}
