/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        // PRD 色系：奶油白底 + 墨绿强调 + 暖棕次要 + 干玫瑰 hover
        surface: '#FAF7F2',
        'surface-bright': '#FFFDF9',
        'surface-dim': '#EDE8E0',
        'surface-container-lowest': '#FFFFFF',
        'surface-container-low': '#F5F0E8',
        'surface-container': '#EDE8DE',
        'surface-container-high': '#E5DFD3',
        'surface-container-highest': '#DDD7CA',
        'surface-variant': '#E8E2D8',
        'on-surface': '#1A1A1A',
        'on-surface-variant': '#5C5650',
        'inverse-surface': '#2C2820',
        'inverse-on-surface': '#F5F0E8',
        outline: '#8B8279',
        'outline-variant': '#C8C0B4',
        primary: '#1A1A1A',
        'on-primary': '#FAF7F2',
        'primary-container': '#2C2820',
        'on-primary-container': '#A09890',
        // 墨绿——强调色（标题 hover、链接 active）
        secondary: '#3D5A40',
        'on-secondary': '#FFFFFF',
        'secondary-container': '#D4E8D6',
        'on-secondary-container': '#1E3320',
        'secondary-fixed': '#D4E8D6',
        'secondary-fixed-dim': '#A8CEAc',
        // 暖棕——次要元素
        tertiary: '#8B6F47',
        'on-tertiary': '#FFFFFF',
        'tertiary-container': '#F0E4D0',
        'on-tertiary-container': '#4A3820',
        'tertiary-fixed-dim': '#C8A880',
        // 干玫瑰——hover 强调（极少使用）
        rose: '#C97B72',
        'on-rose': '#FFFFFF',
        // 雾蓝灰——元数据 / 时间戳
        muted2: '#7A8B99',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        background: '#FAF7F2',
        'on-background': '#1A1A1A',
      },
      borderRadius: {
        DEFAULT: '0px',
        sm: '0px',
        md: '0px',
        lg: '0px',
        xl: '0px',
        full: '0px',
        terminal: '6px',
      },
      spacing: {
        'margin-edge': '48px',
        'section-v-rhyme': '140px',
        gutter: '24px',
        'stack-xl': '44px',
        'stack-lg': '32px',
        'stack-md': '16px',
        'stack-sm': '8px',
      },
      fontFamily: {
        // 英文标题 Playfair Display，中文标题兜底霞鹜文楷 / 思源宋体
        display: ['"Playfair Display"', '"LXGW WenKai"', '"Noto Serif SC"', 'Georgia', 'serif'],
        'headline-lg': ['"Playfair Display"', '"LXGW WenKai"', '"Noto Serif SC"', 'Georgia', 'serif'],
        'headline-lg-mobile': ['"Playfair Display"', '"LXGW WenKai"', '"Noto Serif SC"', 'Georgia', 'serif'],
        'headline-md': ['"Playfair Display"', '"LXGW WenKai"', '"Noto Serif SC"', 'Georgia', 'serif'],
        // 正文：Source Serif 4（英文）+ 思源黑体（中文）
        'body-lg': ['"Source Serif 4"', '"Noto Sans SC"', 'Georgia', 'serif'],
        'body-md': ['"Source Serif 4"', '"Noto Sans SC"', 'Georgia', 'serif'],
        kicker: ['"JetBrains Mono"', 'ui-monospace', 'monospace'],
        'mono-ui': ['"JetBrains Mono"', 'ui-monospace', 'monospace'],
      },
      fontSize: {
        display: ['60px', { lineHeight: '1.15', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-lg': ['48px', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-lg-mobile': ['36px', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-md': ['32px', { lineHeight: '1.3', fontWeight: '600' }],
        'body-lg': ['20px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['17px', { lineHeight: '1.6', fontWeight: '400' }],
        'mono-ui': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        kicker: ['12px', { lineHeight: '1.0', letterSpacing: '0.2em', fontWeight: '500' }],
      },
      maxWidth: {
        prose: '720px',
      },
    },
  },
  plugins: [],
}
